# This is a basic workflow to help you get started with Actions

name: Build Debug

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install seedyrng
          haxelib install random
          haxelib git hscript-plus https://github.com/DleanJeans/hscript-plus/
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools linux
          haxelib install actuate
          haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
          haxelib run lime rebuild extension-webm linux
          haxelib list
      - name: Create APIStuff
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "source/APIStuff.hx"
          FILE_DATA: "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}"
      - name: Compile
        run: haxelib run lime build linux -debug
      - name: Archive
        run: tar -czf bin.tar.gz 'export/debug/linux/bin' 
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linuxBuild
          path: bin.tar.gz
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install seedyrng
          haxelib install random
          haxelib git hscript-plus https://github.com/DleanJeans/hscript-plus/
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools windows
          haxelib install actuate
          haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
          haxelib run lime rebuild extension-webm windows
          haxelib list
        shell: cmd
      - name: Create APIStuff
        run: echo "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}" > source/APIStuff.hx
      - name: Compile
        run: haxelib run lime build windows -debug
      - name: Archive
        run: tar -czf bin.tar.gz export/debug/windows/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: bin.tar.gz
  buildMac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install seedyrng
          haxelib install random
          haxelib git hscript-plus https://github.com/DleanJeans/hscript-plus/
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools macos
          haxelib install actuate
          haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
          haxelib run lime rebuild extension-webm macos
          haxelib list
      - name: Create APIStuff
        run: echo "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}" > source/APIStuff.hx
      - name: Compile
        run: haxelib run lime build mac -debug
      - name: Archive
        run: tar -czf bin.tar.gz export/debug/macos/bin
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macBuild
          path: bin.tar.gz
